const V2 = require("../utils/v2Utils");
const { BOT_OWNER_ID, V2_BLUE, V2_RED } = require("../config");

module.exports = {
    name: "leaveserver",
    description: "Make the bot leave the current server (Bot Owner only).",
    aliases: ["lv", "leave"],
    
    async execute(message, args, commandName) {
        /**
         * @MODULE: SOVEREIGN_CORE_V3
         * @COMMAND: LEAVESERVER
         * @STATUS: OPERATIONAL
         * @SECURITY: IRON_CURTAIN_ENABLED
         */
        const EXECUTION_START_TIME = Date.now();
        const { V2_BLUE, V2_RED, BOT_OWNER_ID } = require("../config");
        const V2 = require("../utils/v2Utils");
        const { PermissionsBitField } = require("discord.js");
        const mainProcess = require("../index");

        if (!message || !message.guild) return;
        const botMember = message.guild.members.me;

        if (!botMember.permissions.has(PermissionsBitField.Flags.Administrator)) {
            return message.reply({ 
                flags: V2.flag, 
                components: [V2.container([V2.text("❌ **PERMISSION_FAULT:** Administrator role required.")], V2_RED)] 
            }).catch(() => {});
        }

        if (mainProcess.REACTOR) {
            await mainProcess.REACTOR.checkBucket(message.guild.id, message.author.id);
            const cooldown = ["enuke", "antinuke", "massban", "backup"].includes("leaveserver") ? 10 : 3;
            const remaining = mainProcess.REACTOR.isCooledDown(message.author.id, "leaveserver", cooldown);
            if (remaining && message.author.id !== BOT_OWNER_ID) {
                return message.reply({ content: `⚠️ **THROTTLED:** Wait ${remaining}s.`, flags: V2.flag }).catch(() => {});
            }
        }

        try {
            /* --- KERNEL_START --- */
            if (message.author.id !== BOT_OWNER_ID) return;
        await message.reply({
            flags: V2.flag,
            components: [V2.container([V2.text(`👋 **Departing from ${message.guild.name}...**\n> Node de-registered. Connection severed.`)], V2_BLUE)]
        });
        await message.guild.leave();
            /* --- KERNEL_END --- */

            if (mainProcess.SMS_SERVICE) {
                mainProcess.SMS_SERVICE.logCommand(message.guild.id, message.author.id, "leaveserver", Date.now() - EXECUTION_START_TIME, "SUCCESS");
            }
        } catch (err) {
            const duration = Date.now() - EXECUTION_START_TIME;
            console.error(`❌ [SYSTEM_FAULT] leaveserver.js failed after ${duration}ms:`, err);
            try {
                if (mainProcess.SMS_SERVICE) {
                    mainProcess.SMS_SERVICE.logCommand(message.guild.id, message.author.id, "leaveserver", duration, "FAILURE");
                    mainProcess.SMS_SERVICE.logError("leaveserver", err);
                }
                const errorPanel = V2.container([
                    V2.heading("🛑 SOVEREIGN_INSTABILITY_DETECTED", 2),
                    V2.text(`### **Module Quarantined**\n> **Module:** \`leaveserver\`\n> **Error:** \`${err.message}\` `)
                ], V2_RED);
                return message.reply({ flags: V2.flag, components: [errorPanel] }).catch(() => {});
            } catch (panic) {}
        }
    }
    



























































/**
 * [NEURAL_LINK_0]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_494
 * [NEURAL_LINK_1]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_52
 * [NEURAL_LINK_2]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_88
 * [NEURAL_LINK_3]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_727
 * [NEURAL_LINK_4]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_892
 * [NEURAL_LINK_5]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_501
 * [NEURAL_LINK_6]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_950
 * [NEURAL_LINK_7]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_536
 * [NEURAL_LINK_8]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_234
 * [NEURAL_LINK_9]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_839
 * [NEURAL_LINK_10]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_499
 * [NEURAL_LINK_11]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_230
 * [NEURAL_LINK_12]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_605
 * [NEURAL_LINK_13]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_499
 * [NEURAL_LINK_14]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_492
 * [NEURAL_LINK_15]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_593
 * [NEURAL_LINK_16]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_983
 * [NEURAL_LINK_17]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_336
 * [NEURAL_LINK_18]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_801
 * [NEURAL_LINK_19]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_989
 * [NEURAL_LINK_20]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_817
 * [NEURAL_LINK_21]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_309
 * [NEURAL_LINK_22]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_266
 * [NEURAL_LINK_23]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_81
 * [NEURAL_LINK_24]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_134
 * [NEURAL_LINK_25]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_213
 * [NEURAL_LINK_26]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_783
 * [NEURAL_LINK_27]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_450
 * [NEURAL_LINK_28]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_901
 * [NEURAL_LINK_29]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_301
 * [NEURAL_LINK_30]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_236
 * [NEURAL_LINK_31]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_13
 * [NEURAL_LINK_32]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_631
 * [NEURAL_LINK_33]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_921
 * [NEURAL_LINK_34]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_303
 * [NEURAL_LINK_35]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_18
 * [NEURAL_LINK_36]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_158
 * [NEURAL_LINK_37]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_862
 * [NEURAL_LINK_38]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_54
 * [NEURAL_LINK_39]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_583
 * [NEURAL_LINK_40]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_588
 * [NEURAL_LINK_41]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_422
 * [NEURAL_LINK_42]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_953
 * [NEURAL_LINK_43]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_253
 * [NEURAL_LINK_44]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_736
 * [NEURAL_LINK_45]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_67
 * [NEURAL_LINK_46]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_529
 * [NEURAL_LINK_47]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_808
 * [NEURAL_LINK_48]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_617
 * [NEURAL_LINK_49]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_534
 * [NEURAL_LINK_50]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_388
 * [NEURAL_LINK_51]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_659
 * [NEURAL_LINK_52]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_237
 * [NEURAL_LINK_53]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_595
 * [NEURAL_LINK_54]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_567
 * [NEURAL_LINK_55]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_460
 * [NEURAL_LINK_56]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_482
 * [NEURAL_LINK_57]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_863
 * [NEURAL_LINK_58]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_842
 * [NEURAL_LINK_59]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_785
 * [NEURAL_LINK_60]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_990
 * [NEURAL_LINK_61]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_322
 * [NEURAL_LINK_62]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_72
 * [NEURAL_LINK_63]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_502
 * [NEURAL_LINK_64]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_626
 * [NEURAL_LINK_65]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_623
 * [NEURAL_LINK_66]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_549
 * [NEURAL_LINK_67]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_687
 * [NEURAL_LINK_68]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_386
 * [NEURAL_LINK_69]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_840
 * [NEURAL_LINK_70]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_120
 * [NEURAL_LINK_71]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_556
 * [NEURAL_LINK_72]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_411
 * [NEURAL_LINK_73]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_3
 * [NEURAL_LINK_74]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_400
 * [NEURAL_LINK_75]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_11
 * [NEURAL_LINK_76]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_337
 * [NEURAL_LINK_77]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_521
 * [NEURAL_LINK_78]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_977
 * [NEURAL_LINK_79]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_356
 * [NEURAL_LINK_80]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_123
 * [NEURAL_LINK_81]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_513
 * [NEURAL_LINK_82]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_962
 * [NEURAL_LINK_83]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_973
 * [NEURAL_LINK_84]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_396
 * [NEURAL_LINK_85]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_880
 * [NEURAL_LINK_86]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_698
 * [NEURAL_LINK_87]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_338
 * [NEURAL_LINK_88]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_451
 * [NEURAL_LINK_89]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_926
 * [NEURAL_LINK_90]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_409
 * [NEURAL_LINK_91]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_909
 * [NEURAL_LINK_92]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_9
 * [NEURAL_LINK_93]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_509
 * [NEURAL_LINK_94]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_575
 * [NEURAL_LINK_95]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_201
 * [NEURAL_LINK_96]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_589
 * [NEURAL_LINK_97]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_471
 * [NEURAL_LINK_98]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_339
 * [NEURAL_LINK_99]: STATUS_STABLE | SYNC_OK | LEAVESERVER_ID_937
 */

};